<?php
$url = $_SERVER['REQUEST_URI'];

if (isset($_POST['username'])) {
    $username = $_POST['username'];
    $target_dir = "uploads/{$username}/";
    $target_file = $target_dir . $username.".webm";
?>
    <html>

    <body>

        <video width="400" controls>
            <source src='<?php echo $target_file?>' type="video/mp4">
            Your browser does not support HTML5 video.
        </video>

        <p>These are the frames' images generated by getVideoImage():</p>
        <ol id="olFrames"></ol>

        <script defer>
            function getVideoImage(path, secs, callback) {
                var me = this,
                    video = document.createElement('video');
                video.onloadedmetadata = function() {
                    if ('function' === typeof secs) {
                        secs = secs(this.duration);
                    }
                    this.currentTime = Math.min(Math.max(0, (secs < 0 ? this.duration : 0) + secs), this.duration);
                };
                video.onseeked = function(e) {
                    var canvas = document.createElement('canvas');
                    canvas.height = video.videoHeight;
                    canvas.width = video.videoWidth;
                    var ctx = canvas.getContext('2d');
                    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
                    var img = new Image();
                    img.src = canvas.toDataURL();
                    callback.call(me, img, this.currentTime, e);
                };
                video.onerror = function(e) {
                    callback.call(me, undefined, undefined, e);
                };
                video.src = path;
            }

            function showImageAt(secs) {
                var duration;
                getVideoImage(
                    '<?php echo $target_file ?>',
                    function(totalTime) {
                        duration = totalTime;
                        return secs;
                    },
                    function(img, secs, event) {
                        if (event.type == 'seeked') {
                            console.log(img.src);
                            $.ajax({
                                type: "POST",
                                url: "http://localhost/frameextract.php",
                                data: {
                                    "base64": img.src,"username":"<?php echo $username;?>"
                                },
                                success: function(result) {

                                }
                            });
                        }
                    }
                );
            }
            let count = 0;
            while (count <= 5) {
                showImageAt(count);
                count++;
            }
        </script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    </body>

    </html>
<?php } ?>